# Generate ChessgroundUnstyled.svelte from Chessground.svelte

use 5.30.0;
use warnings;
use File::Slurper qw/read_text write_text/;

my $unstyled = read_text( 'src/lib/Chessground.svelte' );

# remove entire <style> except for a .cg-wrap{...} at the beginning
$unstyled =~ s@<style>(\s*\.cg-wrap\s+\{.*?\}).*</style>@<style>$1\n</style>@s;

# add file-is-generated comment
$unstyled =~ s@(<script>)@$1\n\t// This file was generated by generate_unstyled.pl\n\t@;

write_text( 'src/lib/ChessgroundUnstyled.svelte', $unstyled );
